Minor Project Edits
1) Removed unused link in the index.html file; and, 2) worked on debugging this error message, "Uncaught (in promise) TypeError: $modalContainer.removeClass is not a function."